/**
 * POST /tools/{{TOOL_NAME}}
 *
 * {{TOOL_SUMMARY}}
 *
 * Generated by @orchet/agent-cli. Edit the body to plug in vendor-
 * specific request shaping or error handling — the boilerplate
 * (bearer extraction, Zod parsing, error envelope) is stable and
 * matches what the orchestrator expects.
 */
import { type NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { extractBearer } from "@/lib/auth";
import { vendorFetch, VendorApiError } from "@/lib/vendor-client";

export const runtime = "edge";
export const dynamic = "force-dynamic";

// Request schema (generated from OpenAPI / docs spec).
const Body = z.object({
  // TODO: tighten this to the actual vendor request shape.
}).passthrough();

export async function POST(req: NextRequest) {
{{#IF HAS_OAUTH}}
  const bearer = extractBearer(req);
  if (!bearer) {
    return NextResponse.json(
      { error: "missing_bearer", code: "connection_required" },
      { status: 401 },
    );
  }
{{/IF}}

  let body: z.infer<typeof Body>;
  try {
    body = Body.parse(await req.json().catch(() => ({})));
  } catch (err) {
    return NextResponse.json(
      { error: "invalid_body", detail: err instanceof Error ? err.message : String(err) },
      { status: 400 },
    );
  }

  try {
    {{TOOL_IMPL_BODY}}
  } catch (err) {
    if (err instanceof VendorApiError) {
      const status = err.status === 401 ? 401 : 502;
      return NextResponse.json(
        { error: "vendor_api_error", status: err.status, detail: err.message },
        { status },
      );
    }
    return NextResponse.json(
      { error: "internal", detail: err instanceof Error ? err.message : String(err) },
      { status: 500 },
    );
  }
}
